apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rubt0m35w-nodejs
  janus-idp.io/tekton: rubt0m35w-nodejs
  backstage.io/kubernetes-id: rubt0m35w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rubt0m35w-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
